### ISSUE TITLE
无网络的时候点击干货详情崩溃啦

### ISSUE THREAD

**Issue by sfsheng0322** [drakeet/Meizhi#15]
09-09 11:14:08.318  21978-22290/? E/AndroidRuntime﹕ FATAL EXCEPTION: OkHttp Dispatcher
    Process: me.drakeet.meizhi, PID: 21978
    java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
            at android.os.Handler.<init>(Handler.java:200)
            at android.os.Handler.<init>(Handler.java:114)
            at android.widget.Toast$TN.<init>(Toast.java:345)
            at android.widget.Toast.<init>(Toast.java:100)
            at android.widget.Toast.makeText(Toast.java:256)
            at me.drakeet.meizhi.util.ToastUtils.showShort(ToastUtils.java:50)
            at me.drakeet.meizhi.ui.GankFragment$1.onFailure(GankFragment.java:161)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:154)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by SharerMax** [comment]
怎么复现，求步骤

**Comment by drakeet** [comment]
这个原因是我的Toast使用问题，最新版已经修正了，apk已更新，代码还没push上来

Saeratom <notifications@github.com>于2015年9月9日周三 22:06写道：
