### ISSUE TITLE
图片预览之后，软件停止

### ISSUE THREAD

**Issue by mingfenghappy** [drakeet/Meizhi#57]

**Comment by drakeet** [comment]
能否提供异常信息日志？

**Comment by mingfenghappy** [comment]
10-09 08:37:37.901 22650-22650/me.drakeet.meizhi E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: me.drakeet.meizhi, PID: 22650
                                                                   java.lang.IllegalStateException: 
The ImageView's ScaleType has been changed since attaching a PhotoViewAttacher
                                                                       at uk.co.senab.photoview.PhotoViewAttacher.checkImageViewScaleType(PhotoViewAttacher.java:684)
                                                                       at uk.co.senab.photoview.PhotoViewAttacher.setImageViewMatrix(PhotoViewAttacher.java:815)
                                                                       at uk.co.senab.photoview.PhotoViewAttacher.resetMatrix(PhotoViewAttacher.java:807)
                                                                       at uk.co.senab.photoview.PhotoViewAttacher.updateBaseMatrix(PhotoViewAttacher.java:892)
                                                                       at uk.co.senab.photoview.PhotoViewAttacher.onGlobalLayout(PhotoViewAttacher.java:423)
                                                                       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:982)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2410)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:158)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
