### ISSUE TITLE
多次在今日肥皂家话题和内容之间点击，会出现空指针

### ISSUE THREAD

**Issue by IrvingRyan** [drakeet/Meizhi#66]
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err: java.lang.NullPointerException
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at me.drakeet.meizhi.ui.WebActivity$ChromeClient.onProgressChanged(WebActivity.java:200)
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.onProgressChanged(WebViewContentsClientAdapter.java:270)
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at com.android.org.chromium.android_webview.AwWebContentsDelegateAdapter.onLoadProgressChanged(AwWebContentsDelegateAdapter.java:39)
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at com.android.org.chromium.components.web_contents_delegate_android.WebContentsDelegateAndroid.notifyLoadProgressChanged(WebContentsDelegateAndroid.java:89)
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:27)
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at android.os.Looper.loop(Looper.java:157)
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5335)
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-28 11:20:44.689 14639-14639/me.drakeet.meizhi.debug W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
12-28 11:20:44.699 14639-14639/me.drakeet.meizhi.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
12-28 11:20:44.699 14639-14639/me.drakeet.meizhi.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
12-28 11:20:44.699 14639-14639/me.drakeet.meizhi.debug W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by drakeet** [comment]
感谢反馈，今晚会排查一下和修复。
